# TODO: remove this in favor of deploying the (automatically built) quay.io/deis/cloudfoundry-github-service-broker:master docker image onto a deis cluster. Upon removal of this manifest, instructions should be added to the INTEGRATION_TESTING.md file on how to set up a broker for testing
apiVersion: v1
kind: ReplicationController
metadata:
  name: sample-broker
  namespace: steward
  labels:
    heritage: deis
spec:
  replicas: 1
  selector:
    app: sample-broker
  template:
    metadata:
      labels:
        app: sample-broker
    spec:
      containers:
        - name: sample-broker
          image: deis/cloudfoundry-github-service-broker:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9292
              name: http
