language: generic
branches:
  only:
    - master
cache:
  directories:
    - vendor
env:
  DEV_REGISTRY=quay.io
services:
  - docker
sudo: required
install:
  - make bootstrap
script:
  - make test test-cover docker-build
deploy:
  provider: script
  script: deploy.sh
  on:
    branch: master

after_success:
  - bash <(curl -s https://codecov.io/bash)
