apiVersion: v1
kind: Service
metadata:
  name: steward
  namespace: steward
  labels:
    heritage: steward
    app: steward
spec:
  ports:
  - port: 80
    name: http
    targetPort: http
  type: LoadBalancer
  selector:
    app: steward
